### ISSUE TITLE
[MODULES-282] EAP cannot load module referenced by target-name

### ISSUE THREAD

**Issue by dmlloyd** [jboss-modules/jboss-modules#377]
@rhusar opened **[MODULES-282](https://issues.redhat.com/browse/MODULES-282?redirect=false)** and commented

Mostly likely introduced by fix for MODULES-241.

Issue reported in EAP by Petr Kremensky:

---

EAP cannot load module referenced by target-name. Trying to use module referenced by old package name "org.jboss.as" ends up with org.jboss.modules.ModuleNotFoundException.

This is a regression against 7.0.0. It was introduced by 1.6.0.Beta5 in EAP 7.1.0.DR13. The issue is blocker for migration from EAP6.

**reproduce**

```
unzip -q jboss-eap-7.1.0.DR15.zip ; cd jboss-eap-7.1
sed -i 's/org.wildfly.clustering.web.infinispan/org.jboss.as.clustering.web.infinispan/' standalone/configuration/standalone.xml
sh bin/standalone.sh

11:03:15,519 ERROR [org.jboss.msc.service.fail] (MSC service thread 1-3) MSC000001: Failed to start service org.wildfly.clustering.infinispan.cache-container.web: org.jboss.msc.service.StartException in service org.wildfly.clustering.infinispan.cache-container.web: org.infinispan.commons.CacheException: Unable to load component metadata!
	at org.wildfly.clustering.service.FunctionalValueService.start(FunctionalValueService.java:69)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:2032)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1955)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.infinispan.commons.CacheException: Unable to load component metadata!
	at org.infinispan.factories.components.ComponentMetadataRepo.initialize(ComponentMetadataRepo.java:111)
	at org.infinispan.factories.GlobalComponentRegistry.<init>(GlobalComponentRegistry.java:106)
	at org.infinispan.manager.DefaultCacheManager.<init>(DefaultCacheManager.java:225)
	at org.jboss.as.clustering.infinispan.subsystem.CacheContainerBuilder.lambda$build$3(CacheContainerBuilder.java:104)
	at org.wildfly.clustering.service.SuppliedValueService.lambda$new$0(SuppliedValueService.java:42)
	at org.wildfly.clustering.service.FunctionalValueService.start(FunctionalValueService.java:67)
	... 5 more
Caused by: java.lang.NullPointerException
	at org.infinispan.factories.components.ComponentMetadataRepo.readMetadata(ComponentMetadataRepo.java:33)
	at org.infinispan.factories.components.ComponentMetadataRepo.initialize(ComponentMetadataRepo.java:109)
	... 10 more
```

---

**Affects:** 1.1.5.GA, 1.2.5.Final, 1.3.8.Final, 1.4.5.Final, 1.5.3.Final, 1.6.0.Beta5, 1.6.0.Beta6

**Issue Links:**
- [JBEAP-10083](https://issues.redhat.com/browse/JBEAP-10083) (7.1.0) EAP cannot load module referenced by target-name
 (_**"clones"**_)
- [MODULES-241](https://issues.redhat.com/browse/MODULES-241) Leaked Alias Modules
 (_**"incorporates"**_)

**Backported to:** [1.5.4.Final](https://github.com/jboss-modules/jboss-modules/milestone/87?closed=1), [1.4.6.Final](https://github.com/jboss-modules/jboss-modules/milestone/80?closed=1), [1.3.9.Final](https://github.com/jboss-modules/jboss-modules/milestone/70?closed=1), [1.2.6.Final](https://github.com/jboss-modules/jboss-modules/milestone/56?closed=1), [1.1.6.GA](https://github.com/jboss-modules/jboss-modules/milestone/47?closed=1)

-1 votes, 5 watchers

**Comment by dmlloyd** [comment]
@ppalaga commented

I created a test that simulates a situation similar to JBEAP-10083 : https://github.com/ppalaga/jboss-modules/commit/ef7b64f563673c4e6fd93c9e2a1ec1283a6e10dc It is failing now but it is passing if the block at ModuleLoader.java#L497 [1] is reverted to the state before MODULES-241.

[1] https://github.com/treblereel/jboss-modules/blob/1.x/src/main/java/org/jboss/modules/ModuleLoader.java#L497

**Comment by dmlloyd** [comment]
@ppalaga commented

The issue is that while in the pre-MODULES-241 implementation the alias module "could see" the direct dependencies of the aliased module, it is not the case anymore after MODULES-241. After MODULES-241, the alias module "can see" only those dependencies of the aliased module, that are exported by the aliased module.

**Comment by dmlloyd** [comment]
**[RH Bugzilla Integration](https://issues.redhat.com/secure/ViewProfile.jspa?name=jira-bugzilla-migration)** commented

Jiří Bílek <jbilek@redhat.com> changed the Status of [bug 1448390](https://bugzilla.redhat.com/show_bug.cgi?id=1448390) from ON_QA to VERIFIED
