### ISSUE TITLE
[MODULES-37] Re-Export depends on module dependency order

### ISSUE THREAD

**Issue by dmlloyd** [jboss-modules/jboss-modules#399]
@tdiesler opened **[MODULES-37](https://issues.redhat.com/browse/MODULES-37?redirect=false)** and commented

Consider

    // ModuleD
    //    +--> ModuleC
    //            +-reex-> ModuleA
    //            +-reex-> ModuleB
    //                        +--> ModuleA

ModuleD is expected to load class from ModuleA - This works

However, with this setup

    // ModuleD
    //    +--> ModuleC
    //            +-reex-> ModuleB
    //            |           +--> ModuleA
    //            +-reex-> ModuleA

ModuleD is cannot load class from ModuleA

The re-export capability of ModuleA seems to get lost. Probably because the paths from ModuleA were already seen without re-export.

---
No further details from [MODULES-37](https://issues.redhat.com/browse/MODULES-37?redirect=false)

**Comment by dmlloyd** [comment]
@tdiesler commented

Running org.jboss.test.osgi.modules.MODULES37TestCase
Tests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.049 sec <<< FAILURE!

testDirectDependencySecond(org.jboss.test.osgi.modules.MODULES37TestCase)  Time elapsed: 0.016 sec  <<< ERROR!
java.lang.ClassNotFoundException: org/jboss/test/osgi/modules/a/A
at java.lang.Class.forName0(Native Method)
at java.lang.Class.forName(Class.java:247)
at org.jboss.modules.Module.loadClass(Module.java:556)
at org.jboss.test.osgi.modules.ModulesTestBase.assertLoadClass(ModulesTestBase.java:92)
at org.jboss.test.osgi.modules.MODULES37TestCase.testDirectDependencySecond(MODULES37TestCase.java:128)

http://github.com/jbosgi/jbosgi-container/blob/d2dfeedf899638c04f1eeed2b8d9fc5c16b66fcf/core/src/test/java/org/jboss/test/osgi/modules/MODULES37TestCase.java
