### ISSUE TITLE
[MODULES-32] All modules must have access to sun.reflect.* on Sun-like JDKs

### ISSUE THREAD

**Issue by dmlloyd** [jboss-modules/jboss-modules#407]
@dmlloyd opened **[MODULES-32](https://issues.redhat.com/browse/MODULES-32?redirect=false)** and commented

Various JDK implementation classes assume that sun.reflect will be accessible from any class loader.  In the example below, sun.reflect.ConstructorAccessorImpl is being instantiated using the class loader which defines the proxy being created by newProxyInstance, because the generated proxy class seems to depend upon it.

java.lang.NoClassDefFoundError: sun/reflect/ConstructorAccessorImpl
at sun.misc.Unsafe.defineClass(Native Method) [:1.6.0_20]
at sun.reflect.ClassDefiner.defineClass(ClassDefiner.java:45) [:1.6.0_20]
at sun.reflect.MethodAccessorGenerator$1.run(MethodAccessorGenerator.java:381) [:1.6.0_20]
at java.security.AccessController.doPrivileged(Native Method) [:1.6.0_20]
at sun.reflect.MethodAccessorGenerator.generate(MethodAccessorGenerator.java:377) [:1.6.0_20]
at sun.reflect.MethodAccessorGenerator.generateConstructor(MethodAccessorGenerator.java:76) [:1.6.0_20]
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:30) [:1.6.0_20]
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27) [:1.6.0_20]
at java.lang.reflect.Constructor.newInstance(Constructor.java:513) [:1.6.0_20]
at java.lang.reflect.Proxy.newProxyInstance(Proxy.java:588) [:1.6.0_20]
at sun.reflect.annotation.AnnotationParser.annotationForMap(AnnotationParser.java:239) [:1.6.0_20]
at sun.reflect.annotation.AnnotationParser.parseAnnotation(AnnotationParser.java:229) [:1.6.0_20]
at sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:69) [:1.6.0_20]
at sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:52) [:1.6.0_20]
at java.lang.reflect.Field.declaredAnnotations(Field.java:1014) [:1.6.0_20]
at java.lang.reflect.Field.getAnnotation(Field.java:1000) [:1.6.0_20]
at java.lang.reflect.AccessibleObject.isAnnotationPresent(AccessibleObject.java:168) [:1.6.0_20]
at com.arjuna.common.internal.util.propertyservice.BeanPopulator.configureFromProperties(BeanPopulator.java:124)
at com.arjuna.common.internal.util.propertyservice.BeanPopulator.getSingletonInstance(BeanPopulator.java:50)
at com.arjuna.ats.arjuna.common.arjPropertyManager.getObjectStoreEnvironmentBean(arjPropertyManager.java:55)
at org.jboss.as.txn.TransactionManagerService.start(TransactionManagerService.java:133)
at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:986)
... 3 more

See also: http://bugs.sun.com/bugdatabase/view_bug.do?bug_id=6265952

We need a solution to possibly extend the set of packages which are always visible.  By default this set only includes "java.*" but possibly sun.reflect should be added as well.  However care must be taken to avoid impacting performance at runtime.

---
No further details from [MODULES-32](https://issues.redhat.com/browse/MODULES-32?redirect=false)

**Comment by dmlloyd** [comment]
@dmlloyd commented

We have an interim solution for now (just add sun.reflect. to the list of forwarded classes).  We can revisit the broader issue later.

**Comment by dmlloyd** [comment]
@dmlloyd commented

Fix incomplete; missing a part on ConcurrentClassLoader
