### ISSUE TITLE
[MODULES-87] Cannot see dependency META-INF/services/* content

### ISSUE THREAD

**Issue by dmlloyd** [jboss-modules/jboss-modules#416]
**[Scott Stark](https://issues.redhat.com/secure/ViewProfile.jspa?name=starksm64)** opened **[MODULES-87](https://issues.redhat.com/browse/MODULES-87?redirect=false)** and commented

I am not seeing the META-INF/services/javax.ws.rs.ext.Providers for the modules on which the main module depends. I should see the services resources for the main module, and its dependency, but only the main module services descriptor is returned from a getResources("META-INF/services/javax.ws.rs.ext.Providers") call.

Here is the output from the org.jboss.modules.ClassPathModuleLoaderTest.testMultipleServices I created:

/System/Library/Frameworks/JavaVM.framework/Versions/1.6/Home/bin/java -Didea.launcher.port=7538 -Didea.launcher.bin.path=/Applications/IntelliJ IDEA 10 CE.app/bin -Dfile.encoding=UTF-8 -classpath /Applications/IntelliJ IDEA 10 CE.app/lib/idea_rt.jar:/Applications/IntelliJ IDEA 10 CE.app/plugins/junit/lib/junit-rt.jar:/System/Library/Frameworks/JavaVM.framework/Versions/A/Resources/Deploy.bundle/Contents/Resources/Java/deploy.jar:/System/Library/Frameworks/JavaVM.framework/Versions/1.6.0/Classes/dt.jar:/System/Library/Frameworks/JavaVM.framework/Versions/A/Resources/Deploy.bundle/Contents/Resources/Java/javaws.jar:/System/Library/Frameworks/JavaVM.framework/Versions/1.6.0/Classes/jce.jar:/System/Library/Frameworks/JavaVM.framework/Versions/1.6.0/Classes/management-agent.jar:/System/Library/Frameworks/JavaVM.framework/Versions/1.6.0/Home/lib/sa-jdi.jar:/System/Library/Frameworks/JavaVM.framework/Versions/1.6.0/Classes/alt-rt.jar:/System/Library/Frameworks/JavaVM.framework/Versions/1.6.0/Classes/charsets.jar:/System/Library/Frameworks/JavaVM.framework/Versions/1.6.0/Classes/classes.jar:/System/Library/Frameworks/JavaVM.framework/Versions/1.6.0/Classes/jconsole.jar:/System/Library/Frameworks/JavaVM.framework/Versions/1.6.0/Classes/jsse.jar:/System/Library/Frameworks/JavaVM.framework/Versions/1.6.0/Classes/ui.jar:/System/Library/Frameworks/JavaVM.framework/Versions/1.6.0/Home/lib/ext/apple_provider.jar:/System/Library/Frameworks/JavaVM.framework/Versions/1.6.0/Home/lib/ext/dnsns.jar:/System/Library/Frameworks/JavaVM.framework/Versions/1.6.0/Home/lib/ext/localedata.jar:/System/Library/Frameworks/JavaVM.framework/Versions/1.6.0/Home/lib/ext/sunjce_provider.jar:/System/Library/Frameworks/JavaVM.framework/Versions/1.6.0/Home/lib/ext/sunpkcs11.jar:/home/git/JBossAS/my-jboss-modules/target/test-classes:/home/git/JBossAS/my-jboss-modules/target/classes:/Users/starksm/.m2/repository/junit/junit/4.7/junit-4.7.jar com.intellij.rt.execution.application.AppMain com.intellij.rt.execution.junit.JUnitStarter -ideVersion5 -junit4 org.jboss.modules.ClassPathModuleLoaderTest,testMultipleServices
modules TRACE: Locally loading module Classpath:main from Class path module loader
modules TRACE: Loaded module Classpath:main from Class path module loader
modules TRACE: Attempting to find all resources META-INF/services/javax.ws.rs.ext.Providers in Module "Classpath:main" from Class path module loader
modules TRACE: Locally loading module test.jaxrs:main from local module loader `@2abe0e27` (roots: /home/git/JBossAS/my-jboss-modules/target/test-classes/test/repo)
modules TRACE: Loaded module test.jaxrs:main from local module loader `@2abe0e27` (roots: /home/git/JBossAS/my-jboss-modules/target/test-classes/test/repo)
modules TRACE: Locally loading module system:main from System Module Loader
modules TRACE: Loaded module system:main from System Module Loader

java.lang.AssertionError: Found 2 services of type javax.ws.rs.ext.Providers expected:<2> but was:<1>
at org.junit.Assert.fail(Assert.java:91)
at org.junit.Assert.failNotEquals(Assert.java:645)
at org.junit.Assert.assertEquals(Assert.java:126)
at org.junit.Assert.assertEquals(Assert.java:470)
at org.jboss.modules.ClassPathModuleLoaderTest.testMultipleServices(ClassPathModuleLoaderTest.java:97)

Process finished with exit code 255

---

**Affects:** 1.0.0.CR3

**Comment by dmlloyd** [comment]
**[Scott Stark](https://issues.redhat.com/secure/ViewProfile.jspa?name=starksm64)** commented

The pull request adds a test which shows how to accomplish this.

**Comment by dmlloyd** [comment]
**[Scott Stark](https://issues.redhat.com/secure/ViewProfile.jspa?name=starksm64)** commented

The dependency needed to include a services="export" to have the META-INF/services in the dependent module seen.
