### ISSUE TITLE
[MODULES-69] Allow for OSGi style Class Filtering

### ISSUE THREAD

**Issue by dmlloyd** [jboss-modules/jboss-modules#439]
@tdiesler opened **[MODULES-69](https://issues.redhat.com/browse/MODULES-69?redirect=false)** and commented

3.6.7 Class Filtering

An exporter can limit the visibility of the classes in a package with the
include and exclude directives on the export definition. The value of each of
these directives is a comma-separated list of class names.

The following example shows an export statement, and a list of files with
their visibility status.

Export-Package: com.acme.foo; include:="Qux*,BarImpl";exclude:=QuxImpl

---

**Affects:** 1.0.0.Beta13

-1 votes, 5 watchers

**Comment by dmlloyd** [comment]
**[David Hildenbrand](https://issues.redhat.com/secure/ViewProfile.jspa?name=bosschaert)** commented

It would be nice to get this one fixed. It causes one of only 2 remaining OSGi Core TCK issues.

**Comment by dmlloyd** [comment]
@dmlloyd commented

Please see the commit at:

https://github.com/jbossas/jboss-modules/commit/aaf4017287598acb

This provides a basic mechanism for filtering classes and resources.  I'm thinking that as a next step, it would make sense to add optional parameters to dependency construction for import/export filters for classes and resources.  Would this satisfy the requirements of the OSGi implementation?

**Comment by dmlloyd** [comment]
@tdiesler commented

I added a low level test case, which is failing

```
 

$ mvn -Dtest=MOD69TestCase install

java.lang.AssertionError: ClassNotFoundException expected for [org.jboss.test.osgi.modules.a.QuxImpl], but was loaded from: ModuleClassLoader for Module "moduleA:main" from ModuleLoaderSupport[default]
	at org.junit.Assert.fail(Assert.java:91)
	at org.jboss.test.osgi.modules.ModulesTestBase.assertLoadClassFails(ModulesTestBase.java:118)
	at org.jboss.test.osgi.modules.MOD69TestCase.testClassFilter(MOD69TestCase.java:122)

```

The test verifies that the filter is working, but fails at the class load level

```
 
        assertTrue(filter.accept(getPath(QuxFoo.class)));
        assertTrue(filter.accept(getPath(QuxBar.class)));
        assertFalse(filter.accept(getPath(QuxImpl.class)));
        assertTrue(filter.accept(getPath(BarImpl.class)));
        
        assertLoadClass(identifierB, QuxFoo.class.getName());
        assertLoadClass(identifierB, QuxBar.class.getName());
        assertLoadClassFails(identifierB, QuxImpl.class.getName());
        assertLoadClass(identifierB, BarImpl.class.getName());

```

https://github.com/tdiesler/jbosgi-framework/commit/6d77646be0de5fb0c6be263b67ed6efe16bbed0a

**Comment by dmlloyd** [comment]
@tdiesler commented

Raised to 'Critical' since this has been blocking OSGi Core 4.2 TCK compliance for a while

**Comment by dmlloyd** [comment]
@dmlloyd commented

In a filtered ResourceLoader, the getClassSpec() method actually matches against the full file name of the class, not the class name, as per the Javadoc, because it works in terms of resources not in terms of classes.  In other words your test filters need ".class" appended to them.

LocalLoaders on the other hand work with classes thus they use ClassFilter.

**Comment by dmlloyd** [comment]
@dmlloyd commented

Reassigning for comment.

**Comment by dmlloyd** [comment]
@tdiesler commented

The behaviour that I am looking for is that ModuleA can load all its local classes (i.e. there is no ClassFilter on the LocalLoader). ModuleA can however set a ClassFilter for its exports.

Currently, I can restrict the exported paths like this

```
        specBuilderA.addDependency(DependencySpec.createLocalDependencySpec(PathFilters.acceptAll(), getPathFilter(A.class)));

        assertLoadClass(identifierA, A.class.getName());
        assertLoadClass(identifierA, B.class.getName());

        assertLoadClass(identifierB, A.class.getName());
        assertLoadClassFails(identifierB, B.class.getName());
```

which covers the use case for entire packages.

Here (https://github.com/tdiesler/jboss-modules/commit/ea03ad5aa02) I added the ability to assign a ClassFilter to the LocalLoader dependency

```
        specBuilderA.addDependency(DependencySpec.createLocalDependencySpec(classFilter));
        addModuleSpec(specBuilderA.create());

        assertLoadClass(identifierA, QuxFoo.class.getName());
        assertLoadClass(identifierA, QuxBar.class.getName());
        //assertLoadClass(identifierA, QuxImpl.class.getName());
        assertLoadClass(identifierA, BarImpl.class.getName());
        
        assertLoadClass(identifierB, QuxFoo.class.getName());
        assertLoadClass(identifierB, QuxBar.class.getName());
        assertLoadClassFails(identifierB, QuxImpl.class.getName());
        assertLoadClass(identifierB, BarImpl.class.getName());
```

This covers the class visibility issue for moduleB. It also breaks class visibility for moduleA's own classes.

Perhaps its possible to change the semantic of the exportFilter for the local dependency such that it works not only on package but also on class level

```
PathFilter exportFilter = PathFilters.match(packagePath + "/Qux*");
specBuilderA.addDependency(DependencySpec.createLocalDependencySpec(PathFilters.acceptAll(), exportFilter));
```

For latest test coverage see: https://github.com/tdiesler/jbosgi-framework/tree/jbosgi441

**Comment by dmlloyd** [comment]
@dmlloyd commented

OK I think I can do this.  I reviewed all the code in question and it definitely seems possible.  Shouldn't take too long...

**Comment by dmlloyd** [comment]
@dmlloyd commented

Resolved in 40846fa8f0954ad1fffeb84dcf00524dbfc4a9d5.

**Comment by dmlloyd** [comment]
@tdiesler commented

The suggested API requires clients to provide a LocalLoader. There is however no public API to get the default LocalLoader when the local dependency is created.

I added a factory method that uses explicit filters, but the default local loader

https://github.com/tdiesler/jboss-modules/commit/7f8da31cb97

A client of that API would look like this

```
        ClassFilter classImportFilter = new ClassFilter() {
            public boolean accept(String className) {
                return true;
            }
        };
        ClassFilter classExportFilter = new ClassFilter() {
            public boolean accept(String className) {
                return filter.accept(className);
            }
        };
        specBuilderA.addResourceRoot(ResourceLoaderSpec.createResourceLoaderSpec(resourceLoaderA));
        PathFilter importFilter = PathFilters.acceptAll();
        PathFilter exportFilter = PathFilters.acceptAll();
        PathFilter resourceImportFilter = PathFilters.acceptAll();
        PathFilter resourceExportFilter = PathFilters.acceptAll();
        specBuilderA.addDependency(DependencySpec.createLocalDependencySpec(importFilter, exportFilter, resourceImportFilter, resourceExportFilter, classImportFilter, classExportFilter));
        addModuleSpec(specBuilderA.create());

        ModuleIdentifier identifierB = ModuleIdentifier.create("moduleB");
        ModuleSpec.Builder specBuilderB = ModuleSpec.build(identifierB);
        specBuilderB.addDependency(DependencySpec.createModuleDependencySpec(identifierA));
        addModuleSpec(specBuilderB.create());
```

The low level test now passes for me

https://github.com/tdiesler/jbosgi-framework/tree/JB[OSGI-441](https://issues.redhat.com/browse/OSGI-441)

```
$ mvn -Dtest=MOD69TestCase test
...
Running org.jboss.test.osgi.modules.MOD69TestCase
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.499 sec
```

I would proceed implementing the OSGi class filter functionality when the suggested (or a similar) change makes it upstream to modules.

**Comment by dmlloyd** [comment]
@dmlloyd commented

Thomas, my last commit on this issue does introduce methods to create dependencies with class and resource filters exactly as you described.

**Comment by dmlloyd** [comment]
@dmlloyd commented

See https://github.com/dmlloyd/jboss-modules/commit/40846fa8f09

**Comment by dmlloyd** [comment]
@dmlloyd commented

Ah oops, my mistake!  I see I missed one.  The method you provided should be fine, I"ll pull that patch in.

**Comment by dmlloyd** [comment]
@dmlloyd commented

Hopefully resolved now :)
