### ISSUE TITLE
[MODULES-111] Regression in Class Filtering

### ISSUE THREAD

**Issue by dmlloyd** [jboss-modules/jboss-modules#470]
@tdiesler opened **[MODULES-111](https://issues.redhat.com/browse/MODULES-111?redirect=false)** and commented

Running org.jboss.test.osgi.modules.MOD69TestCase
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.081 sec <<< FAILURE!

```
java.lang.AssertionError: ClassNotFoundException expected for [org.jboss.test.osgi.modules.a.QuxImpl], but was loaded from: ModuleClassLoader for Module "moduleA:main" from ModuleLoaderSupport[default]
	at org.junit.Assert.fail(Assert.java:91)
	at org.jboss.test.osgi.modules.ModulesTestBase.assertLoadClassFail(ModulesTestBase.java:128)
	at org.jboss.test.osgi.modules.MOD69TestCase.testClassFilter(MOD69TestCase.java:118)
```

https://github.com/tdiesler/jbosgi-framework/tree/mod111

---

**Affects:** 1.1.0.Beta3, 1.1.0.Beta4

**Comment by dmlloyd** [comment]
@tdiesler commented

Here another failing test

Running org.jboss.test.osgi.framework.classloader.ExportFilterTestCase
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.107 sec <<< FAILURE!

**Comment by dmlloyd** [comment]
@dmlloyd commented

Can you be more specific about what is failing?  Else I'm just guessing here.  It would be even better to have a test case against the JBoss Modules codebase.

**Comment by dmlloyd** [comment]
@tdiesler commented

The MOD69TestCase is against the modules code base. You can copy that as is to your repo.
There is an abstraction of a VirtualFileResourceLoader which I believe you also have

**Comment by dmlloyd** [comment]
@tdiesler commented

This regression first appeared in Beta3

**Comment by dmlloyd** [comment]
@dmlloyd commented

I think that this is solved by this commit: http://github.com/dmlloyd/jboss-modules/commit/a419cab but more eyes on this would be helpful.

**Comment by dmlloyd** [comment]
@tdiesler commented

Sorry, still fails with the same cause.

**Comment by dmlloyd** [comment]
@dmlloyd commented

Did you test with my tree?  The commit isn't upstream.

**Comment by dmlloyd** [comment]
@tdiesler commented

Yes I tested with the commit you were given. To test it your self, you can checkout the latest framework, change the modules dependency and remove the `@Ignore` from the test.

**Comment by dmlloyd** [comment]
@dmlloyd commented

I don't really have time to deal with test cases from other code bases.  Unless you want to contribute a test case to the module codebase, or have any other thoughts as to what might be going wrong, I'm going to have to close this issue and move on to other things.

**Comment by dmlloyd** [comment]
@tdiesler commented

For your convenience, here is the test
https://github.com/jbossas/jboss-modules/pull/14

**Comment by dmlloyd** [comment]
@dmlloyd commented

Resolved using contributed test case.  Thanks Thomas.
