### ISSUE TITLE
[MODULES-140] Cannot define class with split packages 

### ISSUE THREAD

**Issue by dmlloyd** [jboss-modules/jboss-modules#480]
@tdiesler opened **[MODULES-140](https://issues.redhat.com/browse/MODULES-140?redirect=false)** and commented

moduleA and moduleB contain ClassA and ClassB respectivly
Both classes come from the same package
ClassA extends ClassB

```
java.lang.ClassNotFoundException: org.jboss.modules.test.ClassA from [Module "moduleA:main" from ModuleLoaderSupport[default]]
	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:190)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:468)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassChecked(ConcurrentClassLoader.java:456)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:398)
	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:120)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at org.jboss.modules.util.ModulesTestBase.loadClass(ModulesTestBase.java:124)
	at org.jboss.modules.util.ModulesTestBase.assertLoadClass(ModulesTestBase.java:94)
	at org.jboss.modules.SplitPackagesTest.testClassFilter(SplitPackagesTest.java:56)
```

---
No further details from [MODULES-140](https://issues.redhat.com/browse/MODULES-140?redirect=false)

**Comment by dmlloyd** [comment]
@tdiesler commented

Here is the test
https://github.com/jbossas/jboss-modules/pull/17

**Comment by dmlloyd** [comment]
@dmlloyd commented

Why should this be supported?

**Comment by dmlloyd** [comment]
@tdiesler commented

It came up during testing related to AS7-5092 as a result of moving classes from one sub deployment to another. We might choose not to support that. Instead of the CNFE it might be possible to give an indication of why the class cannot be loaded.

i.e. "Class org.acme.Foo cannot be defined because of a split package. Found org.acme in moduleA and moduleB"

**Comment by dmlloyd** [comment]
@dmlloyd commented

Yeah it would be nice to be able to add these messages.  This relates back to MODULES-133 wherein I describe the way the JDK "steals" the caused-by exception making it sometimes quite difficult to diagnose class load problems.

I don't currently have any plans to support package splitting across modules, because I don't think there is a clean way to make it work semantically.

**Comment by dmlloyd** [comment]
@tdiesler commented

Can you not issue a warning when moduleA has a dependency on moduleB and both share the same paths?

**Comment by dmlloyd** [comment]
@dmlloyd commented

That's not necessarily a guarantee that this problem will occur.  It's valid to "see" two different packages of the same name.  I think it's only going to fail when you try to link against both at once, via subclassing or composition.  It might be worth doing some testing to see how much this actually occurs in practice.

**Comment by dmlloyd** [comment]
@dmlloyd commented

I do not plan to attempt to support split packages, nor do I know of any way to properly diagnose when this happens.
