### ISSUE TITLE
[MODULES-129] Getting java.lang.NoClassDefFoundError: javax/naming/Context

### ISSUE THREAD

**Issue by dmlloyd** [jboss-modules/jboss-modules#495]
@pmouawad opened **[MODULES-129](https://issues.redhat.com/browse/MODULES-129?redirect=false)** and commented

Hello,
I am in the process of evaluating JBoss Modules in version 1.1.1.GA because I need to avoid my dependencies being exposed to the users of my libraries. Reading http://planet.jboss.org/view/post.seam?post=modularized_java_with_jboss_modules it seems it could be the right solution to my problem.

I started a little test:
package com.ubikingenierie.ubikbatcher;

import org.jboss.modules.Main;

public class UbikBatcherStarter {

    public static void main(String[] args) throws Throwable {
    	String[] newArgs = new String[]{
    		"-config",
    		args[0]+"/config/ubikcb.xml",
    		//"-class",
    		"com.ubikingenierie.consolebatch:6.0.0"
    	};
    	
    	Main.main(newArgs);
    	
    }

}

And I get :
Exception in thread "main" java.lang.NoClassDefFoundError: javax/naming/Context
at java.lang.Class.forName0(Native Method)
at java.lang.Class.forName(Class.java:247)
at org.jboss.modules.Module.run(Module.java:247)
at org.jboss.modules.Main.main(Main.java:291)
at com.ubikingenierie.ubikbatcher.UbikBatcherStarter.main(UbikBatcherStarter.java:15)
Caused by: java.lang.ClassNotFoundException: javax.naming.Context from [Module "com.ubikingenierie.consolebatch:6.0.0" from local module loader @62facf0b (roots: /data/ubs-6.0.0/modules)]
at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:190)
at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:468)
at org.jboss.modules.ConcurrentClassLoader.performLoadClassChecked(ConcurrentClassLoader.java:456)
at org.jboss.modules.ConcurrentClassLoader.performLoadClassChecked(ConcurrentClassLoader.java:423)
at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:398)
at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:120)
... 5 more

Looking at Module.java code, it seems javax.naming.Context is not considered as a System package, is this regular ?
Is there a workaround ?

I don't know if this issue is related to this one:
https://issues.jboss.org/browse/AS7-2442?page=com.atlassian.jira.plugin.system.issuetabpanels:worklog-tabpanel#issue-tabs

Thanks you
Regards
Philippe M.

---

**Affects:** 1.1.1.GA

**Attachments:**
- [module.xml](https://issues.redhat.com/secure/attachment/12352538/module.xml) (_1.86 kB_)
- [ubikcb.xml](https://issues.redhat.com/secure/attachment/12352539/ubikcb.xml) (_264 bytes_)

**Comment by dmlloyd** [comment]
@pmouawad commented

The com.ubikingenierie.consolebatch module

**Comment by dmlloyd** [comment]
@pmouawad commented

The configuration

**Comment by dmlloyd** [comment]
@pmouawad commented

I am not sure but I may have found a fix or maybe that's how it works :
I added to module.xml :
\<system export="true" >
\<paths>
\<path name="javax/naming" />        		
\</paths>
\</system>

If this is OK, then maybe documentation should be updated.

Thanks
Regards
Philippe

**Comment by dmlloyd** [comment]
@dmlloyd commented

No, the only JDK classes which are always included are the java.** packages.  If you want to see how we do this in JBoss AS, look at the `javax.api` module.

**Comment by dmlloyd** [comment]
@dmlloyd commented

Also, for usage questions please refer to forums or IRC, not the bug tracker.

**Comment by dmlloyd** [comment]
@pmouawad commented

Thank you very much for answer.
I am sorry I didn't find the forum or mailing list, now I have done so.
