### ISSUE TITLE
[MODULES-143] JAXP redirect assumes that modules is on the system classpath

### ISSUE THREAD

**Issue by dmlloyd** [jboss-modules/jboss-modules#499]
@tdiesler opened **[MODULES-143](https://issues.redhat.com/browse/MODULES-143?redirect=false)** and commented

In Karaf I see

```
JAXP: using thread context class loader (sun.misc.Launcher$AppClassLoader@35a16869) for search
JAXP: Looking up system property 'javax.xml.validation.SchemaFactory:http://www.w3.org/2001/XMLSchema'
JAXP: The value is '__redirected.__SchemaFactory'
JAXP: createInstance(__redirected.__SchemaFactory)
java.lang.ClassNotFoundException: __redirected.__SchemaFactory
	at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
	at javax.xml.validation.SchemaFactoryFinder.createClass(SchemaFactoryFinder.java:278)
	at javax.xml.validation.SchemaFactoryFinder.createInstance(SchemaFactoryFinder.java:309)
	at javax.xml.validation.SchemaFactoryFinder._newFactory(SchemaFactoryFinder.java:172)
	at javax.xml.validation.SchemaFactoryFinder.newFactory(SchemaFactoryFinder.java:145)
	at javax.xml.validation.SchemaFactory.newInstance(SchemaFactory.java:205)
	at org.apache.aries.blueprint.namespace.NamespaceHandlerRegistryImpl.<init>(NamespaceHandlerRegistryImpl.java:104)
	at org.apache.aries.blueprint.container.BlueprintExtender.start(BlueprintExtender.java:87)
```

---
No further details from [MODULES-143](https://issues.redhat.com/browse/MODULES-143?redirect=false)

**Comment by dmlloyd** [comment]
@tdiesler commented

The jbosgi-framework uses modules internally, but not to bootstrap the OSGi Framework. It should be possible to turn that JAXP redirect off or better enable it explictly

Perhaps like this

```
public static void enableJAXPRedirect() {
   __JAXPRedirected.initAll();
}
```

**Comment by dmlloyd** [comment]
@dmlloyd commented

I think this is incorporated as part of MODULES-136.
