### ISSUE TITLE
[MODULES-133] False NCDFE when super class can not be linked

### ISSUE THREAD

**Issue by dmlloyd** [jboss-modules/jboss-modules#501]
**[Carlo de Wolf](https://issues.redhat.com/secure/ViewProfile.jspa?name=wolfc)** opened **[MODULES-133](https://issues.redhat.com/browse/MODULES-133?redirect=false)** and commented

When https://github.com/jbossas/jboss-dmr/blob/3a46118617083aa339edcbdaf5b3618f324cb277/src/placeholder/java/org/jboss/dmr/Parser.java is used (don't ask) and cookcc is not listed as a module dependency, you get:

```
java.lang.NoClassDefFoundError: org/jboss/dmr/ModelNodeParser
	at org.jboss.dmr.ModelNode.fromString(ModelNode.java:1275)
	at org.jboss.as.cli.operation.impl.DefaultOperationRequestBuilder.addProperty(DefaultOperationRequestBuilder.java:116)
	at org.jboss.as.cli.impl.CommandContextImpl.initialConnection(CommandContextImpl.java:770)
	at org.jboss.as.cli.impl.CommandContextImpl.connectController(CommandContextImpl.java:625)
	at org.jboss.as.cli.handlers.ConnectHandler.doHandle(ConnectHandler.java:109)
	at org.jboss.as.cli.handlers.CommandHandlerWithHelp.handle(CommandHandlerWithHelp.java:84)
	at org.jboss.as.cli.impl.CommandContextImpl.handle(CommandContextImpl.java:458)
	at org.jboss.as.cli.impl.CommandContextImpl.handleSafe(CommandContextImpl.java:469)
	at org.jboss.as.cli.impl.CommandContextImpl.interact(CommandContextImpl.java:1024)
	at org.jboss.as.cli.impl.CliLauncher.main(CliLauncher.java:190)
	at org.jboss.as.cli.CommandLineMain.main(CommandLineMain.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.jboss.modules.Module.run(Module.java:260)
	at org.jboss.modules.Main.main(Main.java:291)
Caused by: java.lang.ClassNotFoundException: org.jboss.dmr.ModelNodeParser from [Module "org.jboss.dmr:main" from local module loader @1fc25624 (roots: /usr/share/jboss-as/modules)]
	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:190)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:468)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassChecked(ConcurrentClassLoader.java:456)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:398)
	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:120)
	... 17 more
```

While the underlying problem (which is quietly consumed) is:

```
java.lang.ClassNotFoundException: org.jboss.dmr.Parser
	at org.jboss.modules.ModuleClassLoader.loadClassLocal(ModuleClassLoader.java:264)
	at org.jboss.modules.ModuleClassLoader$1.loadClassLocal(ModuleClassLoader.java:73)
	at org.jboss.modules.Module.loadModuleClass(Module.java:517)
	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:182)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:468)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassChecked(ConcurrentClassLoader.java:456)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:398)
	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:120)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:791)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at org.jboss.modules.ModuleClassLoader.doDefineOrLoadClass(ModuleClassLoader.java:327)
	at org.jboss.modules.ModuleClassLoader.defineClass(ModuleClassLoader.java:391)
	at org.jboss.modules.ModuleClassLoader.loadClassLocal(ModuleClassLoader.java:243)
	at org.jboss.modules.ModuleClassLoader$1.loadClassLocal(ModuleClassLoader.java:73)
	at org.jboss.modules.Module.loadModuleClass(Module.java:517)
	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:182)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:468)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassChecked(ConcurrentClassLoader.java:456)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:398)
	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:120)
	at org.jboss.dmr.ModelNode.fromString(ModelNode.java:1275)
	at org.jboss.as.cli.operation.impl.DefaultOperationRequestBuilder.addProperty(DefaultOperationRequestBuilder.java:116)
	at org.jboss.as.cli.impl.CommandContextImpl.initialConnection(CommandContextImpl.java:770)
	at org.jboss.as.cli.impl.CommandContextImpl.connectController(CommandContextImpl.java:625)
	at org.jboss.as.cli.handlers.ConnectHandler.doHandle(ConnectHandler.java:109)
	at org.jboss.as.cli.handlers.CommandHandlerWithHelp.handle(CommandHandlerWithHelp.java:84)
	at org.jboss.as.cli.impl.CommandContextImpl.handle(CommandContextImpl.java:458)
	at org.jboss.as.cli.impl.CommandContextImpl.handleSafe(CommandContextImpl.java:469)
	at org.jboss.as.cli.impl.CommandContextImpl.interact(CommandContextImpl.java:1024)
	at org.jboss.as.cli.impl.CliLauncher.main(CliLauncher.java:190)
	at org.jboss.as.cli.CommandLineMain.main(CommandLineMain.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.jboss.modules.Module.run(Module.java:260)
	at org.jboss.modules.Main.main(Main.java:291)
Caused by: java.lang.LinkageError: Failed to link org/jboss/dmr/Parser (Module "org.jboss.dmr:main" from local module loader @7dd09ed4 (roots: /usr/share/jboss-as/modules))
	at org.jboss.modules.ModuleClassLoader.defineClass(ModuleClassLoader.java:396)
	at org.jboss.modules.ModuleClassLoader.loadClassLocal(ModuleClassLoader.java:243)
	... 37 more
Caused by: java.lang.NoClassDefFoundError: org/yuanheng/cookcc/CookCCByte
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:791)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at org.jboss.modules.ModuleClassLoader.doDefineOrLoadClass(ModuleClassLoader.java:327)
	at org.jboss.modules.ModuleClassLoader.defineClass(ModuleClassLoader.java:391)
	... 38 more
Caused by: java.lang.ClassNotFoundException: org.yuanheng.cookcc.CookCCByte from [Module "org.jboss.dmr:main" from local module loader @7dd09ed4 (roots: /usr/share/jboss-as/modules)]
	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:190)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:468)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassChecked(ConcurrentClassLoader.java:456)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:398)
	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:120)
	... 43 more
```

---

**Affects:** 1.1.1.GA

**Issue Links:**
- [MODULES-52](https://issues.redhat.com/browse/MODULES-52) Need a better way to debug NCDFE

**Backported to:** [1.1.5.GA](https://github.com/jboss-modules/jboss-modules/milestone/46?closed=1), [1.0.5.GA](https://github.com/jboss-modules/jboss-modules/milestone/27?closed=1)

**Comment by dmlloyd** [comment]
**[Carlo de Wolf](https://issues.redhat.com/secure/ViewProfile.jspa?name=wolfc)** commented

IMHO the most preferred solution would be to have the LinkageError be the cause of the java.lang.NoClassDefFoundError: org/jboss/dmr/ModelNodeParser.

I'm not sure whether that is even possibly though.

**Comment by dmlloyd** [comment]
@dmlloyd commented

As far as I know it's not possible since we're being called within defineClass.  I considered doing some sort of thread-local hack but I'm not sure it would work 100% reliably (it's better to have it the way it is than to have a falsely connected stack trace added to the main stack trace).

If you can think of a reliable way to do this, I'd consider accepting the patch.

**Comment by dmlloyd** [comment]
@dmlloyd commented

This **might** be fixed or at least mitigated now due to http://github.com/jbossas/jboss-modules/commit/29015b4be5f015f02978e06a96ceca0781cbe6c4 so if there's any way to retest we could possibly close this out.

**Comment by dmlloyd** [comment]
**[Carlo de Wolf](https://issues.redhat.com/secure/ViewProfile.jspa?name=wolfc)** commented

https://github.com/jbossas/jboss-modules/pull/35 shows it is indeed fixed. Nice.
