### ISSUE TITLE
[MODULES-277] definePackage throws IllegalArgumentException for duplicate packages

### ISSUE THREAD

**Issue by dmlloyd** [jboss-modules/jboss-modules#510]
**[Tomaž Cerar](https://issues.redhat.com/secure/ViewProfile.jspa?name=ctomc)** opened **[MODULES-277](https://issues.redhat.com/browse/MODULES-277?redirect=false)** and commented

on jdk9-ea b149 we get following exception when there is duplicate package name in same module

```
java.lang.IllegalArgumentException: org.jboss.as.test.integration.ee.globalmodules
    at java.base/java.lang.ClassLoader.definePackage(ClassLoader.java:2123)
    at org.jboss.modules.ConcurrentClassLoader.definePackage(ConcurrentClassLoader.java:458)
    at org.jboss.modules.ModuleClassLoader.definePackage(ModuleClassLoader.java:579)
    at org.jboss.modules.ModuleClassLoader.definePackage(ModuleClassLoader.java:501)
    at org.jboss.modules.ModuleClassLoader.defineClass(ModuleClassLoader.java:410)
    at org.jboss.modules.ModuleClassLoader.loadClassLocal(ModuleClassLoader.java:275)
    at org.jboss.modules.ModuleClassLoader$1.loadClassLocal(ModuleClassLoader.java:79)
    at org.jboss.modules.Module.loadModuleClass(Module.java:612)
    at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:191)
    at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:377)
    at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:365)
    at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:94)
```

---
No further details from [MODULES-277](https://issues.redhat.com/browse/MODULES-277?redirect=false)

**Comment by dmlloyd** [comment]
@ropalka commented

It was addressed when JPMS support was added to JBoss Modules.
