### ISSUE TITLE
[MODULES-197] javax.mail.api module is not loaded correctly

### ISSUE THREAD

**Issue by dmlloyd** [jboss-modules/jboss-modules#514]
**[Agustin Treceno](https://issues.redhat.com/secure/ViewProfile.jspa?name=atreceno)** opened **[MODULES-197](https://issues.redhat.com/browse/MODULES-197?redirect=false)** and commented

I am trying to use the JBoss mail service with the following class:

```java
import javax.annotation.Resource;
import javax.mail.Address;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;

public class SendMail2 {

  @Resource(mappedName = "java:jboss/mail/Default")
  private static Session mailSession;


  /**
   * @param args
   */
  public static void main(String[] args) {
    try {
      MimeMessage m = new MimeMessage(mailSession);
      Address from = new InternetAddress("agustin@abc.co.uk");
      Address[] to = new InternetAddress[] { new InternetAddress("agustin@abc.co.uk") };

      m.setFrom(from);
      m.setRecipients(Message.RecipientType.TO, to);
      m.setSubject("JBoss AS 7 Mail");
      m.setSentDate(new java.util.Date());
      m.setContent("Mail sent from JBoss AS 7", "text/plain");
      Transport.send(m);
      System.out.println("Mail sent!");
    } catch (MessagingException e) {
      e.printStackTrace();
      System.out.println("Error in Sending Mail: " + e);
    }
  }

}

```

Then compile and execute the class using the jboss module loader:

```
$ javac -classpath /opt/jboss-eap-6.2/modules/system/layers/base/javax/mail/api/main/mail-1.4.5-redhat-1.jar ~/SendMail2.java
$ /usr/java/jdk1.7.0_51/bin/java -jar jboss-modules.jar -mp modules -cp /home/agustin SendMail2
Exception in thread "main" java.lang.NoClassDefFoundError: javax/mail/MessagingException
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:270)
        at org.jboss.modules.Module.run(Module.java:282)
        at org.jboss.modules.Main.main(Main.java:455)
Caused by: java.lang.ClassNotFoundException: javax.mail.MessagingException from [Module "Classpath:main" from Class path module loader for path '/home/agustin']
        at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:197)
        at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:443)
        at org.jboss.modules.ConcurrentClassLoader.performLoadClassChecked(ConcurrentClassLoader.java:431)
        at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:373)
        at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:118)
        ... 4 more
```

As you can see the ModuleClassLoader cannot find the class `javax.mail.MessagingException` which is in the javax.mail.api module.

Now if I specify the JAR of that module in the classpath... it works!

```
$ /usr/java/jdk1.7.0_51/bin/java -jar jboss-modules.jar -mp modules -cp /home/agustin:/opt/jboss-eap-6.2/modules/system/layers/base/javax/mail/api/main/mail-1.4.5-redhat-1.jar SendMail2
Mail sent!
```

More info about the environment:

```
$ uname -a
Linux mars 2.6.32-431.11.2.el6.x86_64 #1 SMP Mon Mar 3 13:32:45 EST 2014 x86_64 x86_64 x86_64 GNU/Linux
$ cat version.txt
JBoss Enterprise Application Platform - Version 6.2.0.GA
$ bin/run.sh -V

========================================================================================

To start a JBoss Enterprise Application Platform 6 Standalone Server, a single
server instance, use the command:

/opt/jboss-eap-6.2/bin/standalone.sh


To start a JBoss Enterprise Application Platform 6 Managed Domain, allowing control
and management of multiple instances, use the command:

/opt/jboss-eap-6.2/bin/domain.sh

========================================================================================
$ /usr/java/jdk1.7.0_51/bin/java -jar jboss-modules.jar -version
JBoss Modules version 1.3.0.Final-redhat-2
```

---

**Affects:** 1.3.0.Final

**Comment by dmlloyd** [comment]
@dmlloyd commented

This is not a bug.  If you want to use a module on the module path, either your JAR must have a Dependencies header in it which references the module (in which case you use the -jar option) or you must list the dependency on the command line.  Classes on the class path do not automatically link against all modules.

For more information, use `java -jar jboss-modules.jar -help`.

**Comment by dmlloyd** [comment]
**[Agustin Treceno](https://issues.redhat.com/secure/ViewProfile.jspa?name=atreceno)** commented

Hi David, I thought one of the purposes of jboss-modules was to resolve the dependencies automatically so I didn't need to specify the dependencies on the command line. Could you please clarify this? Thanks for your help.

**Comment by dmlloyd** [comment]
@dmlloyd commented

No, this is not what it does.  It resolves dependencies that you specify, and provides isolated class loader environments for each module.  It prevents cross-pollution between modules and allows the environment to strictly control which modules can see which other modules.  But there is nothing which automatically browses your code and decides what its dependencies are.  Such an algorithm would necessarily be sloppy at best and outright wrong in the more likely case, especially with a complex module environment.
