### ISSUE TITLE
[MODULES-100] ConcurrentClassLoader is too concurrent for pre Java7

### ISSUE THREAD

**Issue by dmlloyd** [jboss-modules/jboss-modules#536]
**[Adrian Brock](https://issues.redhat.com/secure/ViewProfile.jspa?name=warjort)** opened **[MODULES-100](https://issues.redhat.com/browse/MODULES-100?redirect=false)** and commented

The new ConcurrentClassLoader doesn't work with java6 and before.

It basically removes all locking to avoid deadlocks which means you will get all sorts of race conditions in the classloading which will lead to spurious error messages.

---

**Affects:** 1.1.0.Beta1

**Attachments:**
- [ConcurrentClassLoaderTest.java](https://issues.redhat.com/secure/attachment/12345611/ConcurrentClassLoaderTest.java) (_6.38 kB_)

**Comment by dmlloyd** [comment]
**[Adrian Brock](https://issues.redhat.com/secure/ViewProfile.jspa?name=warjort)** commented

I'm attaching a modified version of ConcurrentClassLoaderTest that shows the problem.

You'll see stack traces like the following when things go bad.

java.lang.ClassNotFoundException: Failed to load class org.jboss.modules.test.ClassB
at org.jboss.modules.ConcurrentClassLoaderTest$TestConcurrentClassLoader.findClass(ConcurrentClassLoaderTest.java:161)
at org.jboss.modules.ConcurrentClassLoader.performLoadClassChecked(ConcurrentClassLoader.java:381)
at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:330)
at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:123)
at org.jboss.modules.ConcurrentClassLoaderTest$4.run(ConcurrentClassLoaderTest.java:116)
at java.lang.Thread.run(Thread.java:636)
Caused by: java.lang.LinkageError: loader (instance of  org/jboss/modules/ConcurrentClassLoaderTest$TestConcurrentClassLoader): attempted  duplicate class definition for name: "org/jboss/modules/test/ClassB"
at java.lang.ClassLoader.defineClass1(Native Method)
at java.lang.ClassLoader.defineClass(ClassLoader.java:634)
at java.lang.ClassLoader.defineClass(ClassLoader.java:480)
at org.jboss.modules.ConcurrentClassLoaderTest$TestConcurrentClassLoader.findClass(ConcurrentClassLoaderTest.java:159)
... 5 more
Exception in thread "Thread-197" java.lang.AssertionError: Failed to load class org.jboss.modules.test.ClassB
at org.junit.Assert.fail(Assert.java:91)
at org.jboss.modules.ConcurrentClassLoaderTest$4.run(ConcurrentClassLoaderTest.java:119)
at java.lang.Thread.run(Thread.java:636)

**Comment by dmlloyd** [comment]
**[Adrian Brock](https://issues.redhat.com/secure/ViewProfile.jspa?name=warjort)** commented

Incidentaly this Assert.fail(), like the other tests in this class, doesn't cause the test to fail
since it occurs on a background thread.
All these tests do is check the background threads finish, not whether there are any errors.
Nor do they validate they loaded the correct class from the correct classloader.

**Comment by dmlloyd** [comment]
@dmlloyd commented

This is perhaps a documentation issue more than anything else.  Because of the lockless way that the class loader operates, when a new class is defined you need to catch a linkage error to detect this race like in this pseudocode:

```
log.trace("Defining class %s", name);
try {
  newClass = defineClass(...);
} catch (LinkageError e) {
  newClass = findLoadedClass(name);
  if (newClass != null) { return newClass; }
  throw e;
}
```

See `ModuleClassLoader` for a more detailed example.

**Comment by dmlloyd** [comment]
@dmlloyd commented

Actually it's probably better to add some methods to CCL to do this to avoid confusion, so that's the approach I'll take.

**Comment by dmlloyd** [comment]
@dmlloyd commented

This change was implemented and the test was fixed.

https://github.com/jbossas/jboss-modules/commit/6457a049b6
https://github.com/jbossas/jboss-modules/commit/f0784edac3

**Comment by dmlloyd** [comment]
**[Adrian Brock](https://issues.redhat.com/secure/ViewProfile.jspa?name=warjort)** commented

That "kludge" is effectively what Java7 does for concurrent classloaders. :-)

However, Java6 (at least in early releases) still had spurious LinkageErrors.
The only way to fix them is/was to retry the whole classloading request from the start, not just the current one. i.e. loading A causes B to be loaded and loading B gives the error, but you have to restart from A to make it work.

This usually showed up in more complicated classloading scenarios, like Hibernate or JMS where factories and implementations were in different classloaders but "tightly bound".

e.g. Something like:

API (classloader A)

public interface a.API {
}

IMPL (ClassLoader B);

public class b.FactoryImpl {

    public static API getAPI() {
        return new IMPL();
    }

}
public class b.IMPL  implements a.API {
}

You then get one thread loading a.API competing with another doing FactoryImpl.getAPI();

I think to really tweak the bug you need something like:

public abstract class a.Factory {

    public static API getAPI() {
       // dynamically delegate to b.FactoryImpl using something like the ServiceLoader api
    }

}

The current test where you have totally different classes loaded on different threads is only checking the locking on the classloaders is handled, not the internal races when defining the same classes on different threads.

**Comment by dmlloyd** [comment]
@dmlloyd commented

Yeah I'm 100% sure we could use more and better tests.  I haven't seen evidence of spurious class loader errors like you describe though.  Since we retry the class load at the "innermost" level I would think that we could avoid this kind of issue.  I will try out some stuff on some older JDKs though and see if I can trip something.

The difference between CCL and JDK 7 concurrency is locking.  JDK 7 uses a fine-grained, per-class-name lock for defineClass; we simply retry in case of collision and avoid locking, which seems to yield better performance according to our measurements.
