### ISSUE TITLE
[MODULES-196] Maven artifact download fails if configured repository URL does not end with slash

### ISSUE THREAD

**Issue by dmlloyd** [jboss-modules/jboss-modules#548]
@dmlloyd opened **[MODULES-196](https://issues.redhat.com/browse/MODULES-196?redirect=false)** and commented

Maven artifact download fails if configured repository URL does not end with slash.

```
testWithPassedRepository(org.jboss.modules.MavenResourceTest)  Time elapsed: 5.827 sec  <<< ERROR!
org.jboss.modules.ModuleLoadException: Error loading module from /Users/david/src/java/jboss-modules/target/test-classes/test/repo/test/maven/main/module.xml
	at org.jboss.modules.ModuleXmlParser.parseModuleXml(ModuleXmlParser.java:154)
	at org.jboss.modules.ModuleXmlParser.parseModuleXml(ModuleXmlParser.java:131)
	at org.jboss.modules.LocalModuleFinder$1.run(LocalModuleFinder.java:154)
	at org.jboss.modules.LocalModuleFinder$1.run(LocalModuleFinder.java:148)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.jboss.modules.LocalModuleFinder.findModule(LocalModuleFinder.java:148)
	at org.jboss.modules.ModuleLoader.findModule(ModuleLoader.java:456)
	at org.jboss.modules.ModuleLoader.loadModuleLocal(ModuleLoader.java:359)
	at org.jboss.modules.ModuleLoader.preloadModule(ModuleLoader.java:306)
	at org.jboss.modules.ModuleLoader.loadModule(ModuleLoader.java:238)
	at org.jboss.modules.MavenResourceTest.testWithPassedRepository(MavenResourceTest.java:59)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:43)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:76)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Caused by: org.jboss.modules.xml.XmlPullParserException: Failed to add artifact 'org.jboss.resteasy:resteasy-jackson-provider:3.0-beta-1' (position: END_TAG seen ...t name="org.jboss.resteasy:resteasy-jackson-provider:3.0-beta-1"/>... @27:83) caused by: java.io.FileNotFoundException: https://repository.jboss.org/nexus/content/groups/publicorg/jboss/resteasy/resteasy-jackson-provider/3.0-beta-1/resteasy-jackson-provider-3.0-beta-1.pom
	at org.jboss.modules.ModuleXmlParser.parseArtifact(ModuleXmlParser.java:750)
	at org.jboss.modules.ModuleXmlParser.parseResources(ModuleXmlParser.java:647)
	at org.jboss.modules.ModuleXmlParser.parseModuleContents(ModuleXmlParser.java:445)
	at org.jboss.modules.ModuleXmlParser.parseDocument(ModuleXmlParser.java:264)
	at org.jboss.modules.ModuleXmlParser.parseModuleXml(ModuleXmlParser.java:152)
	... 34 more
```

Note the "publicorg" which should be "public/org"

---

**Affects:** 1.3.4.Final, 1.4.0.Beta1

**Backported to:** [1.3.5.Final](https://github.com/jboss-modules/jboss-modules/milestone/66?closed=1)

**Comment by dmlloyd** [comment]
**[Tomaž Cerar](https://issues.redhat.com/secure/ViewProfile.jspa?name=ctomc)** commented

Fix with extra test sent
