### ISSUE TITLE
[MODULES-163] Allow Dependencies: header to be empty, don't throw exception or fail deployment startup

### ISSUE THREAD

**Issue by dmlloyd** [jboss-modules/jboss-modules#564]
**[Darryl Miles](https://issues.redhat.com/secure/ViewProfile.jspa?name=dlmiles)** opened **[MODULES-163](https://issues.redhat.com/browse/MODULES-163?redirect=false)** and commented

Exception throw for empty "Dependencies:" header in MANIFEST.MF.

This is a perfectly well-formed header and should have the same meaning as if the header does not exist.

By all means emit a warning explaining which JAR the MANIFEST.MF is in, the header name and that the value is an empty string and this is not allow (due to some spec/rule you cite).

But don't fail a deployment from starting.

Sometimes headers are not going to be perfect from dependent JARs you have little control over.  You don't want to make the user do extra work of repacking/fixing those JAR just to get them to deploy on JBoss AS.

If the empty header has a special meaning then I suggest you use a keyword token instead.  Like you do for "export", "services" and "optional".

---

**Affects:** 1.2.0.CR1

**Issue Links:**
- [WFLY-1090](https://issues.redhat.com/browse/WFLY-1090) Allow Dependencies: header to be empty, don't throw exception or fail deployment startup
 (_**"is cloned by"**_)

**Comment by dmlloyd** [comment]
**[Darryl Miles](https://issues.redhat.com/secure/ViewProfile.jspa?name=dlmiles)** commented

https://en.wikipedia.org/wiki/Robustness_principle  applies

Example of JBoss AS  EAP6.1 failing a deployment:

08:33:34,269 ERROR [org.jboss.msc.service.fail] (MSC service thread 1-9) MSC00001: Failed to start service jboss.deployment.subunit."com.domain.ear.ear"."com-domain-ejb-0.0.1-SNAPSHOT.jar".PARSE: org.jboss.msc.service.StartException in service jboss.deployment.subunit."com.domain.ear.ear"."com-domain-ejb-0.0.1-SNAPSHOT.jar".PARSE: JBAS018733: Failed to process phase PARSE of subdeployment "com-domain-ejb-0.0.1-SNAPSHOT.jar" of deployment "com.domain.ear.ear"
at org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:127) [jboss-as-server-7.2.0.Alpha1-redhat-4.jar:7.2.0.Alpha1-redhat-4]
at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1811) [jboss-msc-1.0.4.GA.jar:1.0.4.GA]
at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1746) [jboss-msc-1.0.4.GA.jar:1.0.4.GA]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [rt.jar:1.7.0_17]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [rt.jar:1.7.0_17]
at java.lang.Thread.run(Thread.java:722) [rt.jar:1.7.0_17]
Caused by: java.lang.IllegalArgumentException: Empty module specification
at org.jboss.modules.ModuleIdentifier.fromString(ModuleIdentifier.java:169) [jboss-modules.jar:1.2.0.CR1]
at org.jboss.as.server.deployment.module.ManifestDependencyProcessor.deploy(ManifestDependencyProcessor.java:92) [jboss-as-server-7.2.0.Alpha1-redhat-4.jar:7.2.0.Alpha1-redhat-4]
at org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:120) [jboss-as-server-7.2.0.Alpha1-redhat-4.jar:7.2.0.Alpha1-redhat-4]
... 5 more

**Comment by dmlloyd** [comment]
@dmlloyd commented

Inside of JBoss Modules itself, the code is already robust against an empty Dependencies attribute.
