### ISSUE TITLE
[MODULES-380] MODULES-339 causes SchemaFactory ServiceLoader.parse Illegal provider-class name when JAXP impl in classpath

### ISSUE THREAD

**Issue by dmlloyd** [jboss-modules/jboss-modules#584]
**[Brad Maxwell](https://issues.redhat.com/secure/ViewProfile.jspa?name=bmaxwell)** opened **[MODULES-380](https://issues.redhat.com/browse/MODULES-380?redirect=false)** and commented

MODULES-339 causes SchemaFactory ServiceLoader.parse Illegal provider-class name when JAXP impl in classpath

```
16:36:44,487 ERROR [org.jboss.msc.service.fail] (ServerService Thread Pool -- 74) MSC000001: Failed to start service jboss.deployment.unit."packaged-xml-parsers.war".undertow-deployment: org.jboss.msc.service.StartException in service jboss.deployment.unit."packaged-xml-parsers.war".undertow-deployment: javax.xml.validation.SchemaFactoryConfigurationError: Provider for class javax.xml.validation.SchemaFactory cannot be created
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:81)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1985)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1487)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1378)
	at java.lang.Thread.run(Thread.java:748)
	at org.jboss.threads.JBossThread.run(JBossThread.java:485)
Caused by: javax.xml.validation.SchemaFactoryConfigurationError: Provider for class javax.xml.validation.SchemaFactory cannot be created
	at javax.xml.validation.SchemaFactoryFinder.findServiceProvider(SchemaFactoryFinder.java:362)
	at javax.xml.validation.SchemaFactoryFinder._newFactory(SchemaFactoryFinder.java:219)
	at javax.xml.validation.SchemaFactoryFinder.newFactory(SchemaFactoryFinder.java:146)
	at javax.xml.validation.SchemaFactory.newInstance(SchemaFactory.java:213)
	at com.redhat.examples.servlet.Servlet.init(Servlet.java:52)
	at io.undertow.servlet.core.LifecyleInterceptorInvocation.proceed(LifecyleInterceptorInvocation.java:117)
	at org.wildfly.extension.undertow.security.RunAsLifecycleInterceptor.init(RunAsLifecycleInterceptor.java:78)
	at io.undertow.servlet.core.LifecyleInterceptorInvocation.proceed(LifecyleInterceptorInvocation.java:103)
	at io.undertow.servlet.core.ManagedServlet$DefaultInstanceStrategy.start(ManagedServlet.java:300)
	at io.undertow.servlet.core.ManagedServlet.createServlet(ManagedServlet.java:140)
	at io.undertow.servlet.core.DeploymentManagerImpl$2.call(DeploymentManagerImpl.java:583)
	at io.undertow.servlet.core.DeploymentManagerImpl$2.call(DeploymentManagerImpl.java:554)
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:42)
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at org.wildfly.extension.undertow.security.SecurityContextThreadSetupAction.lambda$create$0(SecurityContextThreadSetupAction.java:105)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502)
	at io.undertow.servlet.core.DeploymentManagerImpl.start(DeploymentManagerImpl.java:596)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentService.startContext(UndertowDeploymentService.java:97)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:78)
	... 8 more
Caused by: java.util.ServiceConfigurationError: javax.xml.validation.SchemaFactory: vfs:/content/packaged-xml-parsers.war/WEB-INF/lib/jaxp-ri-2.0.jar/META-INF/services/javax.xml.validation.SchemaFactory:1: Illegal provider-class name: http\://www.w3.org/2001/XMLSchema=com.sun.org.apache.xerces.internal.jaxp.validation.xs.SchemaFactoryImpl
	at java.util.ServiceLoader.fail(ServiceLoader.java:239)
	at java.util.ServiceLoader.fail(ServiceLoader.java:245)
	at java.util.ServiceLoader.parseLine(ServiceLoader.java:272)
	at java.util.ServiceLoader.parse(ServiceLoader.java:307)
	at java.util.ServiceLoader.access$200(ServiceLoader.java:185)
	at java.util.ServiceLoader$LazyIterator.hasNextService(ServiceLoader.java:357)
	at java.util.ServiceLoader$LazyIterator.hasNext(ServiceLoader.java:393)
	at java.util.ServiceLoader$1.hasNext(ServiceLoader.java:474)
	at javax.xml.validation.SchemaFactoryFinder$2.run(SchemaFactoryFinder.java:351)
	at javax.xml.validation.SchemaFactoryFinder$2.run(SchemaFactoryFinder.java:347)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.xml.validation.SchemaFactoryFinder.findServiceProvider(SchemaFactoryFinder.java:347)
	... 29 more
```

---

**Affects:** 1.8.6.Final

**Issue Links:**
- [JBEAP-15757](https://issues.redhat.com/browse/JBEAP-15757) [GSS](7.2.z) MODULES-339 caused classloading issue when application packages JAXP implementation
 (_**"is incorporated by"**_)

**Comment by dmlloyd** [comment]
@ropalka commented

There's invalid file content there. jaxp-ri-2.0.jar!/META-INF/services/javax.xml.validation.SchemaFactory contains this line:
http\://www.w3.org/2001/XMLSchema=com.sun.org.apache.xerces.internal.jaxp.validation.xs.SchemaFactoryImpl
but first line should be:
com.sun.org.apache.xerces.internal.jaxp.validation.xs.SchemaFactoryImpl
Other service definitions in META-INF/services are OK.
