### ISSUE TITLE
[MODULES-396] Standalone Build not working

### ISSUE THREAD

**Issue by dmlloyd** [jboss-modules/jboss-modules#627]
@boris-unckel opened **[MODULES-396](https://issues.redhat.com/browse/MODULES-396?redirect=false)** and commented

After a simple git clone https://github.com/jboss-modules/jboss-modules.git and running a build both maven plugins and junit test fail. Eclipse can't build the project. Please find details below. Full Build Log attached. I hope I didn't miss the some documentation about
preparation.
Unfortunaly this bug stops me from backporting the javaagent feature of jboss-modules, which seems to be the reason for https://issues.redhat.com/browse/WFCORE-4805

**java -version**
openjdk version "9.0.4"
OpenJDK Runtime Environment (build 9.0.4+11)
OpenJDK 64-Bit Server VM (build 9.0.4+11, mixed mode)

**mvn -version**
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /opt/maven
Java version: 9.0.4, vendor: Oracle Corporation, runtime: /opt/jdk-9.0.4+11
Default locale: de_DE, platform encoding: UTF-8
OS name: "linux", version: "5.4.12-200.fc31.x86_64", arch: "amd64", family: "unix"

**Plugin**
[INFO] --- bridger:1.4.Final:transform (weave) @ jboss-modules ---
Failed to transform /home/boris_unckel/vhv/jboss-modules/target/classes/META-INF/versions/9/__redirected/JDKSpecific.class: java.lang.IllegalArgumentException
Failed to transform /home/boris_unckel/vhv/jboss-modules/target/classes/META-INF/versions/9/__redirected/JDKSpecific$7.class: java.lang.IllegalArgumentException
Failed to transform /home/boris_unckel/vhv/jboss-modules/target/classes/META-INF/versions/9/__redirected/JDKSpecific$2.class: java.lang.IllegalArgumentException
Failed to transform /home/boris_unckel/vhv/jboss-modules/target/classes/META-INF/versions/9/__redirected/JDKSpecific$10.class: java.lang.IllegalArgumentException
Failed to transform /home/boris_unckel/vhv/jboss-modules/target/classes/META-INF/versions/9/__redirected/JDKSpecific$3.class: java.lang.IllegalArgumentException
Failed to transform /home/boris_unckel/vhv/jboss-modules/target/classes/META-INF/versions/9/__redirected/JDKSpecific$8.class: java.lang.IllegalArgumentException
Failed to transform /home/boris_unckel/vhv/jboss-modules/target/classes/META-INF/versions/9/__redirected/JDKSpecific$4.class: java.lang.IllegalArgumentException
Failed to transform /home/boris_unckel/vhv/jboss-modules/target/classes/META-INF/versions/9/__redirected/JDKSpecific$5.class: java.lang.IllegalArgumentException
Failed to transform /home/boris_unckel/vhv/jboss-modules/target/classes/META-INF/versions/9/__redirected/JDKSpecific$6.class: java.lang.IllegalArgumentException
Failed to transform /home/boris_unckel/vhv/jboss-modules/target/classes/META-INF/versions/9/__redirected/JDKSpecific$9.class: java.lang.IllegalArgumentException
Failed to transform /home/boris_unckel/vhv/jboss-modules/target/classes/META-INF/versions/9/__redirected/JDKSpecific$1.class: java.lang.IllegalArgumentException
Failed to transform /home/boris_unckel/vhv/jboss-modules/target/classes/META-INF/versions/9/org/jboss/modules/JDKSpecific.class: java.lang.IllegalArgumentException
Failed to transform /home/boris_unckel/vhv/jboss-modules/target/classes/META-INF/versions/9/org/jboss/modules/NamedClassLoader.class: java.lang.IllegalArgumentException
Failed to transform /home/boris_unckel/vhv/jboss-modules/target/classes/META-INF/versions/9/org/jboss/modules/xml/JDKSpecific.class: java.lang.IllegalArgumentException
Failed to transform /home/boris_unckel/vhv/jboss-modules/target/classes/META-INF/versions/9/org/jboss/modules/JDKSpecific$1.class: java.lang.IllegalArgumentException
Failed to transform /home/boris_unckel/vhv/jboss-modules/target/classes/META-INF/versions/9/org/jboss/modules/JDKSpecific$JrtFileVisitor.class: java.lang.IllegalArgumentException
Failed to transform /home/boris_unckel/vhv/jboss-modules/target/classes/META-INF/versions/9/org/jboss/modules/maven/JDKSpecific.class: java.lang.IllegalArgumentException
[INFO] Translated 12 methods and 0 method calls

**JUnit**
INFO] Running org.jboss.modules.MavenResourceTest
[ERROR] Tests run: 3, Failures: 0, Errors: 1, Skipped: 1, Time elapsed: 1.272 s <<< FAILURE! - in org.jboss.modules.MavenResourceTest
[ERROR] testDefaultRepositories(org.jboss.modules.MavenResourceTest)  Time elapsed: 0.705 s  <<< ERROR!
org.jboss.modules.ModuleLoadException: Error loading module from /home/boris_unckel/vhv/jboss-modules/target/test-classes/test/repo/test/maven/non-main/module.xml
at org.jboss.modules.xml.ModuleXmlParser.parseModuleXml(ModuleXmlParser.java:304)
at org.jboss.modules.xml.ModuleXmlParser.parseModuleXml(ModuleXmlParser.java:260)
at org.jboss.modules.xml.ModuleXmlParser.parseModuleXml(ModuleXmlParser.java:221)
at org.jboss.modules.LocalModuleFinder.parseModuleXmlFile(LocalModuleFinder.java:250)
at org.jboss.modules.LocalModuleFinder.lambda$findModule$1(LocalModuleFinder.java:195)
at java.base/java.security.AccessController.doPrivileged(Native Method)
at org.jboss.modules.LocalModuleFinder.findModule(LocalModuleFinder.java:195)
at org.jboss.modules.ModuleLoader.findModule0(ModuleLoader.java:693)
at org.jboss.modules.ModuleLoader.findModule(ModuleLoader.java:686)
at org.jboss.modules.ModuleLoader.loadModuleLocal(ModuleLoader.java:496)
at org.jboss.modules.ModuleLoader.preloadModule(ModuleLoader.java:399)
at org.jboss.modules.ModuleLoader.loadModule(ModuleLoader.java:292)
at org.jboss.modules.ModuleLoader.loadModule(ModuleLoader.java:280)
at org.jboss.modules.MavenResourceTest.testDefaultRepositories(MavenResourceTest.java:76)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
at org.junit.rules.RunRules.evaluate(RunRules.java:20)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:272)
at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:236)
at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
Caused by: org.jboss.modules.xml.XmlPullParserException: Failed to add artifact 'xerces:xercesImpl:2.11.0.SP5' (position: END_TAG seen ...-2"/>  -->\n        \<artifact name="xerces:xercesImpl:2.11.0.SP5"/>... `@26`:56) caused by: java.util.zip.ZipException: zip file is empty
at org.jboss.modules.xml.ModuleXmlParser.parseArtifact(ModuleXmlParser.java:979)
at org.jboss.modules.xml.ModuleXmlParser.parseResources(ModuleXmlParser.java:869)
at org.jboss.modules.xml.ModuleXmlParser.parseModuleContents(ModuleXmlParser.java:659)
at org.jboss.modules.xml.ModuleXmlParser.parseDocument(ModuleXmlParser.java:426)
at org.jboss.modules.xml.ModuleXmlParser.parseModuleXml(ModuleXmlParser.java:302)
... 40 more
Caused by: java.util.zip.ZipException: zip file is empty
at java.base/java.util.zip.ZipFile$Source.zerror(ZipFile.java:1252)
at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1072)
at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1160)
at java.base/java.util.zip.ZipFile$Source.\<init>(ZipFile.java:997)
at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:960)
at java.base/java.util.zip.ZipFile.\<init>(ZipFile.java:216)
at java.base/java.util.zip.ZipFile.\<init>(ZipFile.java:148)
at java.base/java.util.jar.JarFile.\<init>(JarFile.java:324)
at org.jboss.modules.maven.JDKSpecific.getJarFile(JDKSpecific.java:33)
at org.jboss.modules.maven.MavenArtifactUtil.createMavenArtifactLoader(MavenArtifactUtil.java:193)
at org.jboss.modules.xml.ModuleXmlParser.parseArtifact(ModuleXmlParser.java:977)
... 44 more

---

**Affects:** 1.7.0.Final, 1.9.2.Final

**Attachments:**
- [sysout.txt](https://issues.redhat.com/secure/attachment/12464170/sysout.txt) (_49.11 kB_)

**Comment by dmlloyd** [comment]
**[Boris Unckel](https://issues.redhat.com/secure/ViewProfile.jspa?name=a13397)** commented

Three different issues:
1) Solved in actual versions (but not in 1.7.0.Final): org/jboss/modules/MavenResourceTest.java had two tests, now splitted up in two files, see below.

2) https://github.com/jboss-modules/jboss-modules/blob/1.x/src/test/java/org/jboss/modules/MavenResourceTest.java does contain hardcoded URLs. We're behind a Firewall/http-Proxy. It would be great to have a INFO Log which URL is used in the regular build output. (Console Level)

3) https://github.com/jboss-modules/jboss-modules/blob/1.x/src/test/java/org/jboss/modules/MavenResource2Test.java utilizes https://github.com/jboss-modules/jboss-modules/blob/1.x/src/test/resources/org/jboss/modules/maven/jboss-settings.xml . We're behind a Firewall/http-Proxy. It would be great to have a INFO Log which URL is used in the regular build output. (Console Level)

For both 2 and 3 a "How to build and test JBoss Modules" document or readme would be great.

_Still open:_
[INFO] — bridger:1.4.Final:transform (weave) @ jboss-modules —
Failed to transform /home/boris_unckel/vhv/jboss-modules/target/classes/META-INF/versions/9/__redirected/JDKSpecific.class: java.lang.IllegalArgumentException

**Comment by dmlloyd** [comment]
@dmlloyd commented

We're doing upstream CI now so this kind of problem should be reproducible.
