### ISSUE TITLE
[MODULES-269] module.xml  schema checking should log errors when it encounters them

### ISSUE THREAD

**Issue by dmlloyd** [jboss-modules/jboss-modules#645]
**[Tom Fonteyne](https://issues.redhat.com/secure/ViewProfile.jspa?name=tfonteyn)** opened **[MODULES-269](https://issues.redhat.com/browse/MODULES-269?redirect=false)** and commented

When defining a JDBC driver, we made a syntax error in the module.xml

\<resources>
\<resource-root path="driver.jar"/>
\</resoruces>

Note the misspelled closing tag "\</resoruces>"

The driver did not get loaded (logically) but no error message was logged in server.log about this

---

**Issue Links:**
- [WFCORE-55](https://issues.redhat.com/browse/WFCORE-55) bad error message for invalid \<resource-root> path in module.xml
 (_**"is duplicated by"**_)

**Comment by dmlloyd** [comment]
@dmlloyd commented

Testing with a simple case, I got this error:

```
Exception in thread "main" org.jboss.modules.ModuleLoadException: Error loading module from /home/david/src/java/wildfly/build/target/wildfly-8.0.1.Final-SNAPSHOT/modules/system/layers/base/org/jboss/as/standalone/main/module.xml
	at org.jboss.modules.ModuleXmlParser.parseModuleXml(ModuleXmlParser.java:155)
	at org.jboss.modules.ModuleXmlParser.parseModuleXml(ModuleXmlParser.java:132)
	at org.jboss.modules.LocalModuleFinder$1.run(LocalModuleFinder.java:154)
	at org.jboss.modules.LocalModuleFinder$1.run(LocalModuleFinder.java:148)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.jboss.modules.LocalModuleFinder.findModule(LocalModuleFinder.java:148)
	at org.jboss.modules.ModuleLoader.findModule(ModuleLoader.java:455)
	at org.jboss.modules.ModuleLoader.loadModuleLocal(ModuleLoader.java:358)
	at org.jboss.modules.ModuleLoader.preloadModule(ModuleLoader.java:305)
	at org.jboss.modules.ModuleLoader.loadModule(ModuleLoader.java:238)
	at org.jboss.modules.Main.main(Main.java:385)
Caused by: org.jboss.modules.xml.XmlPullParserException: end tag name </resouruces> must match start tag name <resources> from line 32 (position: TEXT seen ...<resources>\n    </resouruces>... @33:18) 
	at org.jboss.modules.xml.MXParser.parseEndTag(MXParser.java:1686)
	at org.jboss.modules.xml.MXParser.nextImpl(MXParser.java:1128)
	at org.jboss.modules.xml.MXParser.next(MXParser.java:1090)
	at org.jboss.modules.xml.MXParser.nextTag(MXParser.java:1077)
	at org.jboss.modules.ModuleXmlParser.parseResources(ModuleXmlParser.java:563)
	at org.jboss.modules.ModuleXmlParser.parseModuleContents(ModuleXmlParser.java:394)
	at org.jboss.modules.ModuleXmlParser.parseDocument(ModuleXmlParser.java:219)
	at org.jboss.modules.ModuleXmlParser.parseModuleXml(ModuleXmlParser.java:153)
	... 10 more
```

I think perhaps the newer pull parser might be more strict about this.  If JDBC driver errors however are still not being logged, then it might be a bug in the driver loading code, where it doesn't log exceptions properly.

**Comment by dmlloyd** [comment]
@bstansberry commented

Tom, I'm going to assume WFLY-3571 is a dup of this and will deal with this according to my comment there.

**Comment by dmlloyd** [comment]
@dmlloyd commented

This problem is not reproducible in JBoss Modules.  It may be a bug for the data sources subsystem in WildFly, but it's also possible that Agroal will render the problem moot anyway.
