### ISSUE TITLE
[MODULES-212] Static method form dependency aren't reacheable

### ISSUE THREAD

**Issue by dmlloyd** [jboss-modules/jboss-modules#682]
**[Danila  Sofinskii](https://issues.redhat.com/secure/ViewProfile.jspa?name=dansofinskiy)** opened **[MODULES-212](https://issues.redhat.com/browse/MODULES-212?redirect=false)** and commented

I have module with class like this:

```java
public class Context {
    public static <T> T doLookup(String jndiName) throws JndiLookupException {
       /*...*/
    }
}
```

,
which I use like context provider. This module is static (with module.xml)
But when I call static method from another static module, I have ClassNotFoundException:

```java
Caused by: java.lang.NoClassDefFoundError: our/packag/Context
	at our.packag.AbstractTask.<init>(AbstractTask.java:36)
	at our.packag.AbstractTask.<init>(AbstractTask.java:18)
	at our.packag.ConcreteTask.<init>(ConcreteTask.java:14)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [rt.jar:1.8.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) [rt.jar:1.8.0_45]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [rt.jar:1.8.0_45]
	at java.lang.reflect.Method.invoke(Method.java:497) [rt.jar:1.8.0_45]
```

When I make this method non-static, all works correct. Why classloader don't load module in static case?

---

**Affects:** 1.3.3.Final

**Comment by dmlloyd** [comment]
@dmlloyd commented

Unfortunately this is a usage problem.  It looks like you're simply missing a necessary dependency.  You might want to try the WildFly user forums for help.
