### ISSUE TITLE
[MODULES-364] Circular reference when loading JDKModuleFinder

### ISSUE THREAD

**Issue by dmlloyd** [jboss-modules/jboss-modules#690]
**[George Gastaldi](https://issues.redhat.com/secure/ViewProfile.jspa?name=gastaldi)** opened **[MODULES-364](https://issues.redhat.com/browse/MODULES-364?redirect=false)** and commented

Having a test like:

```java
import org.jboss.modules.JDKModuleFinder;
import org.junit.Test;

public class SmokeTest
{
   @Test
   public void test()
   {
      JDKModuleFinder.getInstance();
   }
}
```

It fails with:

```
Caused by: java.lang.IllegalArgumentException: Module finder cannot be null
	at org.jboss.modules.ModuleLoader.safeClone(ModuleLoader.java:193)
	at org.jboss.modules.ModuleLoader.<init>(ModuleLoader.java:174)
	at org.jboss.modules.ModuleLoader.<init>(ModuleLoader.java:183)
	at org.jboss.modules.Utils.<clinit>(Utils.java:44)
	... 27 more
```

This looks to be caused by circular references in the code.

---

**Affects:** 1.8.1.Final

**Comment by dmlloyd** [comment]
**[George Gastaldi](https://issues.redhat.com/secure/ViewProfile.jspa?name=gastaldi)** commented

Fixed with MODULES-364

**Comment by dmlloyd** [comment]
**[George Gastaldi](https://issues.redhat.com/secure/ViewProfile.jspa?name=gastaldi)** commented

Fixed with MODULES-362, not 364
