### ISSUE TITLE
[MODULES-418] NoClassDefFoundError when using switch statement on enum

### ISSUE THREAD

**Issue by dmlloyd** [jboss-modules/jboss-modules#697]
**[Patrick Johnson](https://issues.redhat.com/secure/ViewProfile.jspa?name=JIRAUSER176518)** opened **[MODULES-418](https://issues.redhat.com/browse/MODULES-418?redirect=false)** and commented

```java
java.lang.NoClassDefFoundError: org/apache/geode/internal/net/BufferPool$1java.lang.NoClassDefFoundError: org/apache/geode/internal/net/BufferPool$1 at org.apache.geode.internal.net.BufferPool.releaseBuffer(BufferPool.java:288) at org.apache.geode.internal.net.ByteBufferVendor$ByteBufferSharingInternalImpl.releaseBuffer(ByteBufferVendor.java:219) at org.apache.geode.internal.net.ByteBufferVendor.dropReference(ByteBufferVendor.java:150) at org.apache.geode.internal.net.ByteBufferVendor.destruct(ByteBufferVendor.java:115) at org.apache.geode.internal.tcp.Connection.run(Connection.java:1519) at java.lang.Thread.run(Thread.java:748)
```

A NoClassDefFoundError for an anonymous inner class is thrown when using a switch statement on an enum. The problem goes away if the switch is replaced with an if/else. This should not happen, switch statements should not break.

---

**Affects:** 1.12.0.Final

**Backported to:** [2.1.6.Final](https://github.com/jboss-modules/jboss-modules/milestone/154?closed=1)

**Comment by dmlloyd** [comment]
@dmlloyd commented

This is actually caused by a bug in `javac`, but since these classes are out in the wild already, there's no point in blaming. The proposed PR should alleviate the issue by fixing up invalid class names.
