### ISSUE TITLE
[MODULES-266] RuntimeException: _clsFromJar when starting EAP on IBM JDK

### ISSUE THREAD

**Issue by dmlloyd** [jboss-modules/jboss-modules#744]
**[Rostislav Svoboda](https://issues.redhat.com/secure/ViewProfile.jspa?name=rsvoboda)** opened **[MODULES-266](https://issues.redhat.com/browse/MODULES-266?redirect=false)** and commented

Starting EAP 7.1.0.DR4 build on IBM jdk fails with the following exception:

```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at java.lang.J9VMInternals.ensureError(J9VMInternals.java:141)
	at java.lang.J9VMInternals.recordInitializationFailure(J9VMInternals.java:130)
	at __redirected.__JAXPRedirected.initAll(__JAXPRedirected.java:81)
	at org.jboss.modules.Module$1.run(Module.java:133)
	at org.jboss.modules.Module$1.run(Module.java:120)
	at java.security.AccessController.doPrivileged(AccessController.java:594)
	at org.jboss.modules.Module.<clinit>(Module.java:120)
	at org.jboss.modules.Main.main(Main.java:390)
Caused by: java.lang.RuntimeException: _clsFromJar
	at java.lang.Class.getDeclaredField(Class.java:779)
	at __redirected.__XMLReaderFactory.<clinit>(__XMLReaderFactory.java:66)
	... 6 more
```

---

**Affects:** 1.6.0.Beta2

**Issue Links:**
- [JBEAP-5903](https://issues.redhat.com/browse/JBEAP-5903) RuntimeException: _clsFromJar when starting EAP on IBM JDK
 (_**"clones"**_)

**Comment by dmlloyd** [comment]
**[Marek Kopecky](https://issues.redhat.com/secure/ViewProfile.jspa?name=mkopecky)** commented

[dlloyd@redhat.com](https://issues.redhat.com/secure/ViewProfile.jspa?name=dlloyd@redhat.com): PR is merged. This jira should be closed, right?
