### ISSUE TITLE
[MODULES-177] Permission check failed for java.io.FilePermission in ModularURLStreamHandlerFactory.createURLStreamHandler

### ISSUE THREAD

**Issue by dmlloyd** [jboss-modules/jboss-modules#753]
**[Alessio Soldano](https://issues.redhat.com/secure/ViewProfile.jspa?name=asoldano)** opened **[MODULES-177](https://issues.redhat.com/browse/MODULES-177?redirect=false)** and commented

Still trying JBossWS testsuite on WFLY master with SecurityManager on...

```
Caused by: java.net.MalformedURLException: WFSM000001: Permission check failed for ("java.io.FilePermission" "/dati/wildfly-prove-sm/modules/system/layers/base/org/jboss/vfs/main/jboss-vfs-3.2.0.Beta1.jar" "read")
	at java.net.URL.<init>(URL.java:619) [rt.jar:1.7.0_17]
	at java.net.URL.<init>(URL.java:482) [rt.jar:1.7.0_17]
	at java.net.URL.<init>(URL.java:431) [rt.jar:1.7.0_17]
	at org.jboss.test.ws.jaxws.cxf.bus.AbstractClient.performSOAPCall(AbstractClient.java:159) [jaxws-cxf-bus-ejb3-client.jar:]
	... 76 more
Caused by: java.security.AccessControlException: WFSM000001: Permission check failed for ("java.io.FilePermission" "/dati/wildfly-prove-sm/modules/system/layers/base/org/jboss/vfs/main/jboss-vfs-3.2.0.Beta1.jar" "read")
	at org.wildfly.security.manager.WildFlySecurityManager.checkPermission(WildFlySecurityManager.java:221)
	at org.wildfly.security.manager.WildFlySecurityManager.checkPermission(WildFlySecurityManager.java:130)
	at java.lang.SecurityManager.checkRead(SecurityManager.java:888) [rt.jar:1.7.0_17]
	at org.wildfly.security.manager.WildFlySecurityManager.checkRead(WildFlySecurityManager.java:273)
	at java.util.zip.ZipFile.<init>(ZipFile.java:205) [rt.jar:1.7.0_17]
	at java.util.zip.ZipFile.<init>(ZipFile.java:144) [rt.jar:1.7.0_17]
	at java.util.jar.JarFile.<init>(JarFile.java:153) [rt.jar:1.7.0_17]
	at java.util.jar.JarFile.<init>(JarFile.java:90) [rt.jar:1.7.0_17]
	at sun.net.www.protocol.jar.URLJarFile.<init>(URLJarFile.java:93) [rt.jar:1.7.0_17]
	at sun.net.www.protocol.jar.URLJarFile.getJarFile(URLJarFile.java:69) [rt.jar:1.7.0_17]
	at sun.net.www.protocol.jar.JarFileFactory.get(JarFileFactory.java:88) [rt.jar:1.7.0_17]
	at sun.net.www.protocol.jar.JarURLConnection.connect(JarURLConnection.java:122) [rt.jar:1.7.0_17]
	at sun.net.www.protocol.jar.JarURLConnection.getInputStream(JarURLConnection.java:150) [rt.jar:1.7.0_17]
	at java.net.URL.openStream(URL.java:1037) [rt.jar:1.7.0_17]
	at java.util.ServiceLoader.parse(ServiceLoader.java:296) [rt.jar:1.7.0_17]
	at java.util.ServiceLoader.access$200(ServiceLoader.java:181) [rt.jar:1.7.0_17]
	at java.util.ServiceLoader$LazyIterator.hasNext(ServiceLoader.java:349) [rt.jar:1.7.0_17]
	at java.util.ServiceLoader$1.hasNext(ServiceLoader.java:439) [rt.jar:1.7.0_17]
	at org.jboss.modules.ModularURLStreamHandlerFactory.createURLStreamHandler(ModularURLStreamHandlerFactory.java:99) [jboss-modules.jar:1.3.0.Beta3]
	at java.net.URL.getURLStreamHandler(URL.java:1150) [rt.jar:1.7.0_17]
	at java.net.URL.<init>(URL.java:590) [rt.jar:1.7.0_17]
	... 79 more
```

---

**Affects:** 1.3.0.Beta3

**Backported to:** [1.3.0.Beta4](https://github.com/jboss-modules/jboss-modules/milestone/60?closed=1)

**Comment by dmlloyd** [comment]
@n1hility commented

Can you give this a try:

https://github.com/n1hility/jboss-modules/commit/448612b4cd816bc42ef9959450d62753760383d7

I will need to think about the security ramnifications

**Comment by dmlloyd** [comment]
**[Alessio Soldano](https://issues.redhat.com/secure/ViewProfile.jspa?name=asoldano)** commented

Hi Jason, I've just tested the fix and it's working. Thanks.
