### ISSUE TITLE
[MODULES-116] Locking issue with sun.misc.Launcher$AppClassLoader

### ISSUE THREAD

**Issue by dmlloyd** [jboss-modules/jboss-modules#767]
@tdiesler opened **[MODULES-116](https://issues.redhat.com/browse/MODULES-116?redirect=false)** and commented

In Jekins the OSGi example testsuite consistently fails with errors like this

https://hudson.qa.jboss.com/hudson/view/JBossOSGi/job/jbosgi-embedded/1753/

```
05:48:18,038 ERROR [org.jboss.osgi.framework.FutureServiceValue] (main) ThreadInfo: "MSC service thread 1-8" Id=19 RUNNABLE
	at java.lang.String.concat(String.java:2000)
	at java.net.URLClassLoader.isSealed(URLClassLoader.java:357)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:241)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:307)
	-  locked sun.misc.Launcher$AppClassLoader@138d107f
	...

	Number of locked synchronizers = 1
	- java.util.concurrent.locks.ReentrantLock$NonfairSync@67071c84


05:48:18,039 ERROR [org.jboss.osgi.framework.FutureServiceValue] (main) ThreadInfo: "MSC service thread 1-7" Id=18 BLOCKED on sun.misc.Launcher$AppClassLoader@138d107f owned by "MSC service thread 1-8" Id=19
	at org.jboss.osgi.framework.internal.URLHandlerPlugin.registerStreamHandlerService(URLHandlerPlugin.java:155)
	-  blocked on sun.misc.Launcher$AppClassLoader@138d107f
	at org.jboss.osgi.framework.internal.URLHandlerPlugin.start(URLHandlerPlugin.java:126)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1824)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1759)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:662)

	Number of locked synchronizers = 1
	- java.util.concurrent.locks.ReentrantLock$NonfairSync@3e0d1329

```

---

**Affects:** 1.1.0.CR2

**Attachments:**
- [example-test.log](https://issues.redhat.com/secure/attachment/12348928/example-test.log) (_35.10 kB_)

**Comment by dmlloyd** [comment]
@tdiesler commented

Attaching the full framework log

**Comment by dmlloyd** [comment]
@dmlloyd commented

I don't see any evidence here of anything that is being done by Modules?  All the log messages and stuff all come from OSGi.

**Comment by dmlloyd** [comment]
@dmlloyd commented

Unscheduling until it's clear what the issue is, or even that it is a Modules issue.  Without more specifics and a small self-contained repeatable test case, I will close this issue.

**Comment by dmlloyd** [comment]
@dmlloyd commented

As promised.
