### ISSUE TITLE
[MODULES-45] Unexpected class load with unwired dependency

### ISSUE THREAD

**Issue by dmlloyd** [jboss-modules/jboss-modules#778]
@tdiesler opened **[MODULES-45](https://issues.redhat.com/browse/MODULES-45?redirect=false)** and commented

package org.jboss.test.osgi.modules.c;
import org.jboss.test.osgi.modules.a.A;
public class C
{
static
{
new A();
}
}

ModuleB contains class C but not A. There is no dependency on the module that provides A

In Beta6 I had this code

    try
    {
       Module.loadClass(identifierB, C.class.getName());
       fail("NoClassDefFoundError expected");
    }
    catch (NoClassDefFoundError er)
    {
       // expected
    }

In Beta7 the class loads without error

    ModuleClassLoader classLoader = loadModule(identifierB).getClassLoader();
    Class<?> clazz = classLoader.loadClass(C.class.getName(), true);

NoClassDefFoundError occurs on

    clazz.newInstance();

---

**Affects:** 1.0.0.Beta7

**Comment by dmlloyd** [comment]
@dmlloyd commented

The linking behavior is slightly less aggressive than in the past.  So, some errors are deferred until the class is linked for imports.  However that wouldn't explain this error.  Can you provide a standalone test case which duplicates the problem?

**Comment by dmlloyd** [comment]
@dmlloyd commented

Assigned for more information.

**Comment by dmlloyd** [comment]
@tdiesler commented

https://github.com/jbosgi/jbosgi-framework/blob/bootstrap/core/src/test/java/org/jboss/test/osgi/modules/ModulesTestCase.java

`@Test`
public void testDependencyNotWired() throws Exception
{
JavaArchive archiveA = getModuleA();
ModuleIdentifier identifierA = ModuleIdentifier.create(archiveA.getName());
ModuleSpec.Builder specBuilderA = ModuleSpec.build(identifierA);
specBuilderA.addResourceRoot(new VirtualFileResourceLoader(toVirtualFile(archiveA)));
specBuilderA.addDependency(DependencySpec.createLocalDependencySpec());
addModuleSpec(specBuilderA.create());

      JavaArchive archiveB = getModuleB();
      ModuleIdentifier identifierB = ModuleIdentifier.create(archiveB.getName());
      ModuleSpec.Builder specBuilderB = ModuleSpec.build(identifierB);
      specBuilderB.addResourceRoot(new VirtualFileResourceLoader(toVirtualFile(archiveB)));
      specBuilderB.addDependency(DependencySpec.createLocalDependencySpec());
      addModuleSpec(specBuilderB.create());
    
      assertLoadClass(identifierA, A.class.getName());
      assertLoadClass(identifierA, B.class.getName());
    
      // [TODO] MODULES-45 Unexpected class load with unwired dependency
      // assertLoadClassFails(identifierB, C.class.getName());
      
      Class<?> clazz = loadClass(identifierB, C.class.getName());
      try
      {
         clazz.newInstance();
         fail("NoClassDefFoundError expected");
      }
      catch (NoClassDefFoundError er)
      {
         // expected
      }
      
      assertLoadClass(identifierB, D.class.getName());

}

**Comment by dmlloyd** [comment]
@dmlloyd commented

This is not a standalone test case...

**Comment by dmlloyd** [comment]
@tdiesler commented

> git clone -b bootstrap git://github.com/jbosgi/jbosgi-framework.git
> mvn -Dtest=MOD45TestCase install

Running org.jboss.test.osgi.modules.MOD45TestCase
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.373 sec <<< FAILURE!

**Comment by dmlloyd** [comment]
@dmlloyd commented

I think I have the answer.  If a class is already loaded, attempting to resolve the class with the resolve flag will be ignored.  To test I have a patch here: https://github.com/dmlloyd/jboss-modules/tree/MODULES-45

Can you try it out and see if it solves the issue for you?

**Comment by dmlloyd** [comment]
@tdiesler commented

Could you please rebase this on Beta13 an then reassign back to me?

**Comment by dmlloyd** [comment]
@dmlloyd commented

Rebased.

**Comment by dmlloyd** [comment]
@tdiesler commented

Sorry, still failing

[tdiesler@localhost jbosgi-framework]$ mvn -Dtest=MOD45TestCase test

---

Test set: org.jboss.test.osgi.modules.MOD45TestCase

---

Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.393 sec <<< FAILURE!
testDependencyNotWired(org.jboss.test.osgi.modules.MOD45TestCase)  Time elapsed: 0.254 sec  <<< FAILURE!
java.lang.AssertionError: ClassNotFoundException expected
at org.junit.Assert.fail(Assert.java:91)
at org.jboss.test.osgi.modules.ModulesTestBase.assertLoadClassFails(ModulesTestBase.java:110)
at org.jboss.test.osgi.modules.MOD45TestCase.testDependencyNotWired(MOD45TestCase.java:88)

**Comment by dmlloyd** [comment]
@dmlloyd commented

Mystery solved... (?)

http://java.sun.com/docs/books/jls/third_edition/html/execution.html#12.4.1

ClassLoader#resolveClass() only **links** the class; it doesn't necessarily force it to be initialized.  To initialize the class you can do Class.forName(name, true, classLoader) though.

diff --git a/core/src/test/java/org/jboss/test/osgi/modules/ModulesTestBase.java b/core/src/test/java/org/jboss/test/osgi/modules/ModulesTestBase.java
index eecebf3..54c4f7e 100644
--- a/core/src/test/java/org/jboss/test/osgi/modules/ModulesTestBase.java
+++ b/core/src/test/java/org/jboss/test/osgi/modules/ModulesTestBase.java
@@ -114,7 +114,8 @@ public abstract class ModulesTestBase {
}

    protected Class<?> loadClass(ModuleIdentifier identifier, String className) throws Exception {

- 

      Class<?> clazz = loadModule(identifier).getClassLoader().loadClass(className, true);

+//        Class<?> clazz = loadModule(identifier).getClassLoader().loadClass(className, true);
+

    Class<?> clazz = Class.forName(className, true, loadModule(identifier).getClassLoader());
    return clazz;

}

**Comment by dmlloyd** [comment]
@tdiesler commented

Done

https://github.com/jbosgi/jbosgi-framework/commit/ea4167cddc504fcb94a3fa49ff9f489864e7294e

**Comment by dmlloyd** [comment]
@dmlloyd commented

Removing from release notes.
